site_name: 天佐.主页
site_description: "zhengtianzuo"
site_url: https://zhengtianzuo.com/
repo_url: https://github.com/zhengtianzuo/
copyright: Copyright© 2003-2025 郑天佐. All rights reserved.

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换暗色模式
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换亮色模式
  language: zh
  logo: img/me.png
  favicon: img/me.png
  features:
    - content.code.copy # 代码块复制按钮
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    - navigation.sections # 侧边栏分组显示
    - navigation.indexes # 组标题有专属页面
    - navigation.top # 返回顶部按钮
    - toc.follow # 目录自动跟随
    - search.suggest # 搜索推荐
    - header.autohide # 自动隐藏头部
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/extra.js

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          site_name: tianzuo.home
          name: English
          build: true
          nav_translations:
            主页: home
            技术分享: technology sharing
            个人作品: personal work
            模块: component
            产品: product
            其他: other
            全部文章列表: All Articles
            编程语言: Programming Languages
            网络开发: NetWork
            操作系统: Operating System
            开发工具: Development Tools
            远程桌面: remote desktop
            屏幕捕获: Screen Captures
            视频编解码: Video Codec
            音频编解码: Audio Codec
            鼠标键盘: keyboard Mouse
            文件传输: File Transfer
            数据库: DataBases
            网络通讯: Networks
            安全技术: Security
            剪切板共享: Clipboard
            音频重定向: AudioRedirection
            USB重定向: USBRedirection
            数字水印: Watermarks
            构建: Building
            调试: Debugging
            性能: Performance
            味道: CodeSmell
            存储: Storage
            计算: Calculation
            技巧: Skill
            服务器: Server
  - search
  - mermaid2
  
extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
  generator: false
  social:
    - icon: fontawesome/brands/qq
      link: tencent://message/?uin=278969898&Site=&Menu=yes
    - icon: fontawesome/brands/qq
      link: https://qm.qq.com/q/tWTAELk0ow
    - icon: fontawesome/solid/envelope
      link: mailto:<zhengtianzuo06@163.com>
    - icon: fontawesome/solid/c
      link: https://blog.csdn.net/zhengtianzuo06/
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/camelstudio/
    - icon: simple/juejin
      link: https://juejin.cn/user/4198362625883460
    - icon: material/web
      link: https://my.oschina.net/zhengtianzuo05
    - icon: material/web
      link: https://www.cnblogs.com/zhengtianzuo
    - icon: material/web
      link: https://blog.51cto.com/zhengtianzuo
    - icon: fontawesome/brands/github
      link: https://github.com/zhengtianzuo/
    - icon: fontawesome/solid/g
      link: https://gitee.com/zhengtianzuo/


nav:
  - 主页: index.md
  - 技术分享:
    - 编程语言:
      - C&C++:
        - technology/C++.md
        - UI:
          - Qt:
            - technology/Cpp/QtWidgets.md
            - technology/Cpp/QtQuick.md
          - wxWidgets:
            - technology/Cpp/wxWidgets.md
        - 构建:
          - technology/Cpp/027-7zsfx.md
        - 调试:
          - technology/Cpp/013-Detours.md
          - technology/Cpp/014-log4cpp.md
          - technology/Cpp/022-spdlog.md
          - technology/Cpp/031-valgrind.md
        - 测试:
          - technology/Cpp/010-Catch2.md
          - technology/Cpp/012-Benchmark.md
        - 性能:
          - technology/Cpp/009-HighResolutionClock.md
          - technology/Cpp/029-gperftools.md
          - technology/Cpp/030-gprof.md
        - 味道:
          - technology/Cpp/CodeSmell.md
        - 存储:
          - technology/Cpp/001-BoostMessageQueue.md
          - technology/Cpp/002-BoostSharedMemory.md
          - technology/Cpp/003-BoostFileLock.md
          - technology/Cpp/020-RingQueue.md
          - technology/Cpp/021-TCMalloc.md
          - technology/Cpp/025-lz4.md
          - technology/Cpp/026-zstd.md
        - 计算:
          - technology/Cpp/004-Get_CPU_Useage.md
          - technology/Cpp/005-Get_Mem_Useage.md
          - technology/Cpp/006-GetSerialNumber.md
          - technology/Cpp/008-GenerateUniqueNumbers.md
          - technology/Cpp/011-base64.md
          - technology/Cpp/019-RSA.md
          - technology/Cpp/023-sha256.md
        - 技巧:
          - technology/Cpp/007-PropertyInCpp.md
          - technology/Cpp/015-SingleApplication.md
          - technology/Cpp/016-condition_variable.md
          - technology/Cpp/028-ImageCompress.md
        - 服务器:
          - technology/Cpp/017-HttpServer.md
        - 网络:
          - technology/Cpp/018-IOCP.md
          - technology/Cpp/024-epoll.md
      - Python:
        - technology/Python.md
      - Java:
        - technology/Java.md
      - CSharp:
        - technology/CSharp.md
      - JS:
        - technology/JavaScript.md
      - PHP:
        - technology/PHP.md
      - VB:
        - technology/VisualBasic.md
      - Go:
        - technology/Go.md
      - Rust:
        - technology/Rust.md
      - Ruby:
        - technology/Ruby.md
    - 操作系统:
      - technology/OperatingSystem.md
    - 开发工具:
      - technology/DevelopmentTools.md
  - 远程桌面:
    - 屏幕捕获:
      - remotedesktop/ScreenCaptures.md
    - 视频编解码:
      - remotedesktop/VideoCodec.md
    - 音频编解码:
      - remotedesktop/AudioCodec.md
    - 鼠标键盘:
      - remotedesktop/keyboardMouse.md
    - 文件传输:
      - remotedesktop/FileTransfer.md
    - 数据库:
      - remotedesktop/DataBases.md
    - 网络通讯:
      - remotedesktop/Networks.md
    - 安全技术:
      - remotedesktop/Security.md
    - 剪切板共享:
      - remotedesktop/Clipboard.md
    - 音频重定向:
      - remotedesktop/AudioRedirection.md
    - USB重定向:
      - remotedesktop/USBRedirection.md
    - 数字水印:
      - remotedesktop/Watermarks.md
  - 个人作品:
    - 产品:
      - product/tianzuo.Pangu.md
      - product/tianzuo.Kunlun.md
      - product/tianzuo.Fuxi.md
    - 模块:
      - component/tianzuo.Kongtong.md
      - component/tianzuo.Qiankun.md
      - component/tianzuo.Zhuiri.md
      - component/tianzuo.Hundun.md
      - component/tianzuo.LianYao.md
  - 其他: 
    - other/index.md
  - 全部文章列表:
    - other/AllArticles.md